// ── Auto-generated by orchestrator assembly — do NOT edit manually ──

export type AssetMeta = {
  isSprite?: boolean;
  cols?: number;
  rows?: number;
  frameCount?: number;
};

export const ASSETS: Record<string, string> = {
  "field_soccer_ball": new URL("./assets/models/prop_field-soccer-ball_be41c5.glb", import.meta.url).href,
  "field_soccer_goal": new URL("./assets/models/prop_field-soccer-goal_3a2403.glb", import.meta.url).href,
  "grass-tuft": new URL("./assets/sprite/sprite_grass-tuft_665842.png", import.meta.url).href,
  "ground-grass": new URL("./assets/sprite/sprite_ground-grass_1813ec.png", import.meta.url).href,
  "ground-path": new URL("./assets/sprite/sprite_ground-path_d62b30.png", import.meta.url).href,
  "jersey-argentina-fabric": new URL("./assets/sprite/sprite_jersey-argentina-fabric_d81d80.png", import.meta.url).href,
  "jersey-croatia-fabric": new URL("./assets/sprite/sprite_jersey-croatia-fabric_58ae31.png", import.meta.url).href,
  "jersey-germany-fabric": new URL("./assets/sprite/sprite_jersey-germany-fabric_a0f09e.png", import.meta.url).href,
  "oak-tree": new URL("./assets/sprite/sprite_oak-tree_154b7e.png", import.meta.url).href,
  "portal-cover-adventure": new URL("./assets/sprite/sprite_portal-cover-adventure_7921e1.png", import.meta.url).href,
  "portal-cover-cards": new URL("./assets/sprite/sprite_portal-cover-cards_52fb70.png", import.meta.url).href,
  "portal-cover-defender": new URL("./assets/sprite/sprite_portal-cover-defender_2f613b.png", import.meta.url).href,
  "portal-cover-puzzle": new URL("./assets/sprite/sprite_portal-cover-puzzle_13454b.png", import.meta.url).href,
  "portal-cover-racing": new URL("./assets/sprite/sprite_portal-cover-racing_037b47.png", import.meta.url).href,
  "shirt-galaxy": new URL("./assets/sprite/sprite_shirt-galaxy_2c03ae.png", import.meta.url).href,
  "shirt-geometric": new URL("./assets/sprite/sprite_shirt-geometric_82bec3.png", import.meta.url).href,
  "shirt-tropical": new URL("./assets/sprite/sprite_shirt-tropical_a99ba7.png", import.meta.url).href,
  "shoes-canvas": new URL("./assets/sprite/sprite_shoes-canvas_1442a2.png", import.meta.url).href,
  "shoes-leather": new URL("./assets/sprite/sprite_shoes-leather_232d06.png", import.meta.url).href,
  "stadium-crowd": new URL("./assets/sprite/sprite_stadium-crowd_1c49a4.png", import.meta.url).href,
  "stadium-turf": new URL("./assets/sprite/sprite_stadium-turf_f0a345.png", import.meta.url).href,
  "tex_awning_cloth": new URL("./assets/sprite/sprite_tex-awning-cloth_4334ea.webp", import.meta.url).href,
  "tex_cut_stone": new URL("./assets/sprite/sprite_tex-cut-stone_525147.webp", import.meta.url).href,
  "tex_flagstone": new URL("./assets/sprite/sprite_tex-flagstone_14c15b.webp", import.meta.url).href,
  "tex_wood_planks": new URL("./assets/sprite/sprite_tex-wood-planks_656cc1.webp", import.meta.url).href,
};

export const ASSET_META: Record<string, AssetMeta> = {};
