// ── Auto-generated by orchestrator assembly — do NOT edit manually ──

export type AssetMeta = {
  isSprite?: boolean;
  cols?: number;
  rows?: number;
  frameCount?: number;
};

export const ASSETS: Record<string, string> = {
  "bgm_fair_loop": new URL("./assets/bgm/bgm_bgm-fair-loop_2f7397.mp3", import.meta.url).href,
  "bgm_stadium_calm": new URL("./assets/bgm/bgm_bgm-stadium-calm_060593.mp3", import.meta.url).href,
  "field_soccer_ball": new URL("./assets/models/prop_field-soccer-ball_be41c5.glb", import.meta.url).href,
  "field_soccer_goal": new URL("./assets/models/prop_field-soccer-goal_3a2403.glb", import.meta.url).href,
  "glasses_aviator": new URL("./assets/models/prop_glasses-aviator_d423ef.glb", import.meta.url).href,
  "glasses_browline": new URL("./assets/models/prop_glasses-browline_e6ac1c.glb", import.meta.url).href,
  "glasses_cateye": new URL("./assets/models/prop_glasses-cateye_f0c16d.glb", import.meta.url).href,
  "glasses_heart": new URL("./assets/models/prop_glasses-heart_89e675.glb", import.meta.url).href,
  "glasses_sport": new URL("./assets/models/prop_glasses-sport_6cf23b.glb", import.meta.url).href,
  "grass-tuft": new URL("./assets/sprite/sprite_grass-tuft_665842.png", import.meta.url).href,
  "ground-grass": new URL("./assets/sprite/sprite_ground-grass_1813ec.png", import.meta.url).href,
  "ground-path": new URL("./assets/sprite/sprite_ground-path_d62b30.png", import.meta.url).href,
  "jersey-argentina-fabric": new URL("./assets/sprite/sprite_jersey-argentina-fabric_d81d80.png", import.meta.url).href,
  "jersey-croatia-fabric": new URL("./assets/sprite/sprite_jersey-croatia-fabric_58ae31.png", import.meta.url).href,
  "jersey-germany-fabric": new URL("./assets/sprite/sprite_jersey-germany-fabric_a0f09e.png", import.meta.url).href,
  "oak-tree": new URL("./assets/sprite/sprite_oak-tree_154b7e.png", import.meta.url).href,
  "portal-cover-cards": new URL("./assets/sprite/sprite_portal-cover-cards_abc1fd.webp", import.meta.url).href,
  "portal-cover-dribbler": new URL("./assets/sprite/sprite_portal-cover-dribbler_3b541b.webp", import.meta.url).href,
  "portal-cover-goalie": new URL("./assets/sprite/sprite_portal-cover-goalie_0695f6.webp", import.meta.url).href,
  "portal-cover-juggler": new URL("./assets/sprite/sprite_portal-cover-juggler_fe5b6e.webp", import.meta.url).href,
  "portal-cover-racing": new URL("./assets/sprite/sprite_portal-cover-racing_c7b1b5.webp", import.meta.url).href,
  "poster_worldcup_banner": new URL("./assets/bg/bg_poster-worldcup-banner_e92888.webp", import.meta.url).href,
  "poster_worldcup_portrait": new URL("./assets/portrait/portrait_poster-worldcup-portrait_69e0b1.webp", import.meta.url).href,
  "shirt-galaxy": new URL("./assets/sprite/sprite_shirt-galaxy_2c03ae.png", import.meta.url).href,
  "shirt-geometric": new URL("./assets/sprite/sprite_shirt-geometric_82bec3.png", import.meta.url).href,
  "shirt-tropical": new URL("./assets/sprite/sprite_shirt-tropical_a99ba7.png", import.meta.url).href,
  "shoes-canvas": new URL("./assets/sprite/sprite_shoes-canvas_1442a2.png", import.meta.url).href,
  "shoes-leather": new URL("./assets/sprite/sprite_shoes-leather_232d06.png", import.meta.url).href,
  "stadium-crowd": new URL("./assets/sprite/sprite_stadium-crowd_1c49a4.png", import.meta.url).href,
  "stadium-turf": new URL("./assets/sprite/sprite_stadium-turf_f0a345.png", import.meta.url).href,
  "tex_awning_cloth": new URL("./assets/sprite/sprite_tex-awning-cloth_4334ea.webp", import.meta.url).href,
  "tex_cut_stone": new URL("./assets/sprite/sprite_tex-cut-stone_525147.webp", import.meta.url).href,
  "tex_flagstone": new URL("./assets/sprite/sprite_tex-flagstone_14c15b.webp", import.meta.url).href,
  "tex_wood_planks": new URL("./assets/sprite/sprite_tex-wood-planks_656cc1.webp", import.meta.url).href,
};

export const ASSET_META: Record<string, AssetMeta> = {};
